spring.application.name=Internlink

spring.datasource.url=jdbc:postgresql://localhost:5432/internlink
spring.datasource.username=postgres
spring.datasource.password=Wepia25?
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
